DEFAULT_ASR_TOPIC = '/asr/final_text'
DEFAULT_TTS_TOPIC = '/tts/text'
DEFAULT_VOICE_STATE_TOPIC = '/voice/session_state'
DEFAULT_WAKEUP_TOPIC = '/voice/wakeup'
DEFAULT_WAKE_ACK_TEXT = '我在，你说'
DEFAULT_LLM_MODEL = 'qwen-vl-plus'
DEFAULT_API_KEY = ''
DEFAULT_TIMEOUT_SEC = 30.0
DEFAULT_NUM_PREDICT = 128
DEFAULT_NUM_CTX = 192
DEFAULT_TEMPERATURE = 0.2
DEFAULT_ENABLE_FAST_COMMANDS = True
DEFAULT_ENABLE_INTENT_ROUTING = True
DEFAULT_MAX_RULE_TEXT_LENGTH = 8
DEFAULT_SYSTEM_PROMPT = '你是一个部署在机器人上的中文语音助手，请给出简短、自然、适合播报的回复。'
DEFAULT_ENABLE_VISION = False
DEFAULT_IMAGE_PATH = ''

VOICE_STATE_SLEEPING = 'sleeping'
VOICE_STATE_ACKING = 'acking'
VOICE_STATE_LISTENING = 'listening'
VOICE_STATE_THINKING = 'thinking'
VOICE_STATE_SPEAKING = 'speaking'
VOICE_STATE_ACTIVE = (
    VOICE_STATE_ACKING,
    VOICE_STATE_LISTENING,
    VOICE_STATE_THINKING,
    VOICE_STATE_SPEAKING,
)


def is_voice_active_state(state: str) -> bool:
    return state in VOICE_STATE_ACTIVE
