from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import EnvironmentVariable, LaunchConfiguration
from launch_ros.actions import Node
from kws_ros2.config import (
    DEFAULT_COOLDOWN_SEC,
    DEFAULT_ENGINE,
    DEFAULT_KWS_MODEL_PATH,
    DEFAULT_RESUME_GRACE_SEC,
    DEFAULT_SCORE_THRESHOLD,
    DEFAULT_TRIGGER_COUNT,
)
from sherpa_onnx_ros2.config import (
    DEFAULT_ASR_API_BASE_URL,
    DEFAULT_ASR_API_KEY,
    DEFAULT_ASR_API_MODEL,
    DEFAULT_ASR_LANGUAGE,
    DEFAULT_ASR_MAX_UTTERANCE_MS,
    DEFAULT_ASR_MIN_SPEECH_MS,
    DEFAULT_ASR_PROMPT,
    DEFAULT_ASR_SILENCE_THRESHOLD,
    DEFAULT_ASR_TRAILING_SILENCE_MS,
    DEFAULT_PROVIDER,
)


def generate_launch_description():
    return LaunchDescription([
        DeclareLaunchArgument('api_base_url', default_value=EnvironmentVariable('LLM_API_BASE_URL', default_value='https://ark.cn-beijing.volces.com/api/v3')),
        DeclareLaunchArgument('llm_model', default_value=EnvironmentVariable('LLM_MODEL', default_value='doubao-seed-2-0-mini-260428')),
        DeclareLaunchArgument('llm_api_key', default_value=EnvironmentVariable('LLM_API_KEY', default_value='ark-f9a1b4f7-50f5-4f43-9fc4-cf8b7cc3d320-7e34b')),
        DeclareLaunchArgument('enable_fast_commands', default_value='true'),
        DeclareLaunchArgument('enable_intent_routing', default_value='true'),
        DeclareLaunchArgument('enable_vision', default_value='false'),
        DeclareLaunchArgument('image_path', default_value=''),
        DeclareLaunchArgument('max_rule_text_length', default_value='8'),
        DeclareLaunchArgument('asr_sample_rate', default_value='16000'),
        DeclareLaunchArgument('asr_samples_per_chunk', default_value='800'),
        DeclareLaunchArgument('asr_input_device', default_value='plughw:CARD=Device,DEV=0'),
        DeclareLaunchArgument('asr_min_speech_ms', default_value='250'),
        DeclareLaunchArgument('asr_silence_threshold', default_value='650'),
        DeclareLaunchArgument('asr_provider', default_value=EnvironmentVariable('ASR_PROVIDER', default_value=DEFAULT_PROVIDER)),
        DeclareLaunchArgument('asr_mode', default_value='wake_gated'),
        DeclareLaunchArgument('asr_session_timeout_sec', default_value='10.0'),
        DeclareLaunchArgument('asr_api_base_url', default_value=EnvironmentVariable('ASR_API_BASE_URL', default_value=DEFAULT_ASR_API_BASE_URL)),
        DeclareLaunchArgument('asr_api_key', default_value=EnvironmentVariable('ASR_API_KEY', default_value=DEFAULT_ASR_API_KEY)),
        DeclareLaunchArgument('asr_api_model', default_value=EnvironmentVariable('ASR_API_MODEL', default_value=DEFAULT_ASR_API_MODEL)),
        DeclareLaunchArgument('kws_engine', default_value='bpu_kws'),
        DeclareLaunchArgument('kws_score_threshold', default_value='0.86'),
        DeclareLaunchArgument('kws_trigger_count', default_value=str(DEFAULT_TRIGGER_COUNT)),
        DeclareLaunchArgument('kws_window_ms', default_value='1000'),
        DeclareLaunchArgument('kws_hop_ms', default_value='200'),
        DeclareLaunchArgument('kws_feature_dim', default_value='40'),
        DeclareLaunchArgument('kws_fbank_frame_length_ms', default_value='25.0'),
        DeclareLaunchArgument('kws_fbank_frame_shift_ms', default_value='10.0'),
        DeclareLaunchArgument('kws_fbank_dither', default_value='0.0'),
        DeclareLaunchArgument('kws_model_path', default_value=DEFAULT_KWS_MODEL_PATH),
        DeclareLaunchArgument('kws_cooldown_sec', default_value=str(DEFAULT_COOLDOWN_SEC)),
        DeclareLaunchArgument('kws_resume_grace_sec', default_value=str(DEFAULT_RESUME_GRACE_SEC)),
        DeclareLaunchArgument('wake_ack_text', default_value='我在，你说'),
        DeclareLaunchArgument('takeover_topic', default_value='/voice/takeover'),
        DeclareLaunchArgument('takeover_window_sec', default_value='5.0'),
        DeclareLaunchArgument('voice_idle_timeout_sec', default_value='12.0'),
        DeclareLaunchArgument('tts_proxy', default_value=EnvironmentVariable('HTTPS_PROXY', default_value='http://192.168.137.1:7897')),

        Node(
            package='kws_ros2',
            executable='kws_node',
            name='kws_node',
            output='screen',
            parameters=[{
                'input_device': 'plughw:CARD=Device,DEV=0',
                'sample_rate': LaunchConfiguration('asr_sample_rate'),
                'channels': 1,
                'samples_per_chunk': 1600,
                'wakeup_topic': '/voice/wakeup',
                'voice_state_topic': '/voice/session_state',
                'engine': LaunchConfiguration('kws_engine'),
                'cooldown_sec': LaunchConfiguration('kws_cooldown_sec'),
                'resume_grace_sec': LaunchConfiguration('kws_resume_grace_sec'),
                'wake_words': ['你好番薯', '番薯番薯'],
                'score_threshold': LaunchConfiguration('kws_score_threshold'),
                'trigger_count': LaunchConfiguration('kws_trigger_count'),
                'window_ms': LaunchConfiguration('kws_window_ms'),
                'hop_ms': LaunchConfiguration('kws_hop_ms'),
                'feature_dim': LaunchConfiguration('kws_feature_dim'),
                'fbank_frame_length_ms': LaunchConfiguration('kws_fbank_frame_length_ms'),
                'fbank_frame_shift_ms': LaunchConfiguration('kws_fbank_frame_shift_ms'),
                'fbank_dither': LaunchConfiguration('kws_fbank_dither'),
                'kws_model_path': LaunchConfiguration('kws_model_path'),
            }],
        ),
        Node(
            package='kws_ros2',
            executable='wake_manager',
            name='wake_manager',
            output='screen',
            parameters=[{
                'wakeup_topic': '/voice/wakeup',
                'voice_state_topic': '/voice/session_state',
                'takeover_topic': LaunchConfiguration('takeover_topic'),
                'takeover_window_sec': LaunchConfiguration('takeover_window_sec'),
                'idle_timeout_sec': LaunchConfiguration('voice_idle_timeout_sec'),
            }],
        ),
        Node(
            package='sherpa_onnx_ros2',
            executable='asr_node',
            name='asr_node',
            output='screen',
            parameters=[{
                'input_device': LaunchConfiguration('asr_input_device'),
                'sample_rate': LaunchConfiguration('asr_sample_rate'),
                'channels': 1,
                'samples_per_chunk': LaunchConfiguration('asr_samples_per_chunk'),
                'topic_final': '/asr/final_text',
                'topic_partial': '/asr/partial_text',
                'provider': LaunchConfiguration('asr_provider'),
                'mode': LaunchConfiguration('asr_mode'),
                'wakeup_topic': LaunchConfiguration('takeover_topic'),
                'voice_state_topic': '/voice/session_state',
                'session_timeout_sec': LaunchConfiguration('asr_session_timeout_sec'),
                'wakeup_cooldown_sec': 2.0,
                'api_base_url': LaunchConfiguration('asr_api_base_url'),
                'api_key': LaunchConfiguration('asr_api_key'),
                'api_model': LaunchConfiguration('asr_api_model'),
                'language': DEFAULT_ASR_LANGUAGE,
                'prompt': DEFAULT_ASR_PROMPT,
                'silence_threshold': LaunchConfiguration('asr_silence_threshold'),
                'min_speech_ms': LaunchConfiguration('asr_min_speech_ms'),
                'trailing_silence_ms': DEFAULT_ASR_TRAILING_SILENCE_MS,
                'max_utterance_ms': DEFAULT_ASR_MAX_UTTERANCE_MS,
            }],
        ),
        Node(
            package='voice_interaction',
            executable='dialog_node',
            name='dialog_node',
            output='screen',
            parameters=[{
                'asr_topic': '/asr/final_text',
                'tts_topic': '/tts/text',
                'voice_state_topic': '/voice/session_state',
                'wakeup_topic': LaunchConfiguration('takeover_topic'),
                'wake_ack_text': LaunchConfiguration('wake_ack_text'),
                'api_base_url': LaunchConfiguration('api_base_url'),
                'llm_model': LaunchConfiguration('llm_model'),
                'api_key': LaunchConfiguration('llm_api_key'),
                'system_prompt': '你是一个部署在机器人上的中文语音助手，请给出简短、自然、适合播报的回复。',
                'request_timeout_sec': 90.0,
                'num_predict': 128,
                'num_ctx': 192,
                'temperature': 0.2,
                'enable_fast_commands': LaunchConfiguration('enable_fast_commands'),
                'enable_intent_routing': LaunchConfiguration('enable_intent_routing'),
                'max_rule_text_length': LaunchConfiguration('max_rule_text_length'),
                'enable_vision': LaunchConfiguration('enable_vision'),
                'image_path': LaunchConfiguration('image_path'),
            }],
        ),
        Node(
            package='tts_ros2',
            executable='tts_node',
            name='tts_node',
            output='screen',
            parameters=[{
                'voice': 'zh-CN-XiaoxiaoNeural',
                'rate': '+0%',
                'volume': '+0%',
                'output_device': 'plughw:CARD=Device,DEV=0',
                'tts_topic': '/tts/text',
                'tmp_dir': '/tmp/edge_tts_audio',
                'wake_ack_text': LaunchConfiguration('wake_ack_text'),
                'proxy': LaunchConfiguration('tts_proxy'),
            }],
        ),
    ])

