DEFAULT_INPUT_DEVICE = 'default'
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_CHANNELS = 1
DEFAULT_SAMPLES_PER_CHUNK = 1600
DEFAULT_WAKEUP_TOPIC = '/voice/wakeup'
DEFAULT_VOICE_STATE_TOPIC = '/voice/session_state'
DEFAULT_TAKEOVER_TOPIC = '/voice/takeover'
DEFAULT_TAKEOVER_WINDOW_SEC = 5.0
DEFAULT_VOICE_IDLE_TIMEOUT_SEC = 12.0
DEFAULT_ENGINE = 'bpu_kws'
DEFAULT_WAKE_WORDS = ['你好番薯', '番薯番薯']
DEFAULT_COOLDOWN_SEC = 6.0
DEFAULT_SCORE_THRESHOLD = 0.73
DEFAULT_TRIGGER_COUNT = 2
DEFAULT_RESUME_GRACE_SEC = 1.5
DEFAULT_PAUSE_ON_SPEAKING = False
DEFAULT_WINDOW_MS = 1000
DEFAULT_HOP_MS = 200
DEFAULT_KWS_MODEL_PATH = '/home/sunrise/ros2_ws/src/kws_ros2/kws.bin'
DEFAULT_FEATURE_DIM = 40
DEFAULT_FBANK_FRAME_LENGTH_MS = 25.0
DEFAULT_FBANK_FRAME_SHIFT_MS = 10.0
DEFAULT_FBANK_DITHER = 0.0

VOICE_STATE_SLEEPING = 'sleeping'
VOICE_STATE_ACKING = 'acking'
VOICE_STATE_LISTENING = 'listening'
VOICE_STATE_THINKING = 'thinking'
VOICE_STATE_SPEAKING = 'speaking'
VOICE_STATE_ACTIVE = (
	VOICE_STATE_ACKING,
	VOICE_STATE_LISTENING,
	VOICE_STATE_THINKING,
	VOICE_STATE_SPEAKING,
)


def is_voice_active_state(state: str) -> bool:
	return state in VOICE_STATE_ACTIVE
