DEFAULT_INPUT_DEVICE = 'default'
DEFAULT_SAMPLE_RATE = 16000
DEFAULT_CHANNELS = 1
DEFAULT_SAMPLES_PER_CHUNK = 1600  # 100ms @ 16kHz
DEFAULT_TOPIC_FINAL = '/asr/final_text'
DEFAULT_TOPIC_PARTIAL = '/asr/partial_text'
DEFAULT_PROVIDER = 'openai_compatible'
DEFAULT_MODE = 'wake_gated'
DEFAULT_WAKEUP_TOPIC = '/voice/takeover'
DEFAULT_VOICE_STATE_TOPIC = '/voice/session_state'
DEFAULT_SESSION_TIMEOUT_SEC = 15.0

# 云端 ASR（openai_compatible）
DEFAULT_ASR_API_BASE_URL = 'https://api.siliconflow.cn/v1'
DEFAULT_ASR_API_KEY = 'sk-nfvumctiqgdpxvxhkbvcvukiuoamtraeufmwlnrwmphysgak'
DEFAULT_ASR_API_MODEL = 'FunAudioLLM/SenseVoiceSmall'
DEFAULT_ASR_LANGUAGE = 'zh'
DEFAULT_ASR_PROMPT = ''
DEFAULT_ASR_SILENCE_THRESHOLD = 550
DEFAULT_ASR_MIN_SPEECH_MS = 400
DEFAULT_ASR_TRAILING_SILENCE_MS = 650
DEFAULT_ASR_MAX_UTTERANCE_MS = 10000

VOICE_STATE_SLEEPING = 'sleeping'
VOICE_STATE_ACKING = 'acking'
VOICE_STATE_LISTENING = 'listening'
VOICE_STATE_THINKING = 'thinking'
VOICE_STATE_SPEAKING = 'speaking'
VOICE_STATE_ACTIVE = (
    VOICE_STATE_ACKING,
    VOICE_STATE_LISTENING,
    VOICE_STATE_THINKING,
    VOICE_STATE_SPEAKING,
)
